const colors = {
  light: {
    text: "#0A0E1A",
    tint: "#00A651",
    background: "#F5F7FA",
    foreground: "#0A0E1A",
    card: "#FFFFFF",
    cardForeground: "#0A0E1A",
    primary: "#00A651",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F5EE",
    secondaryForeground: "#007A3D",
    muted: "#F0F2F5",
    mutedForeground: "#6B7280",
    accent: "#FFB700",
    accentForeground: "#0A0E1A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E8ED",
    input: "#E5E8ED",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#00A651",
    background: "#0A0E1A",
    foreground: "#FFFFFF",
    card: "#131929",
    cardForeground: "#FFFFFF",
    primary: "#00A651",
    primaryForeground: "#FFFFFF",
    secondary: "#1A2F22",
    secondaryForeground: "#4ADE80",
    muted: "#1E2A3A",
    mutedForeground: "#9CA3AF",
    accent: "#FFB700",
    accentForeground: "#0A0E1A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E2A3A",
    input: "#1E2A3A",
  },
  radius: 14,
};

export default colors;
