kind = "mobile"
previewPath = "/"
title = "Ke²Connect"
version = "1.0.0"
id = "artifacts/ke2connect"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19416

[services.development]
run = "pnpm --filter @workspace/ke2connect run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ke2connect", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/ke2connect", "run", "serve" ]

[services.env]
PORT = "19416"
BASE_PATH = "/"
